name: Nextflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run syntax & stub tests
    runs-on: ubuntu-latest
    env: 
      NXF_SINGULARITY_CACHEDIR: /tmp/singularity-cache  # move cache out of work/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: latest
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy  # <- install numpy here
          pip install numpy pandas
          pip install -r requirements.txt || true

      - name: Create dummy directories for databases
        run: |
          mkdir -p work/databases/{mobDB,virlencefinder_db,prokka_db,iceberg,phaster}
          mkdir -p test_output
      - name: Install Singularity
        run: |
          sudo apt-get update && sudo apt-get install -y singularity-container
      - name: Set up Miniconda and create ETE3 environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ete3_env.yml
          activate-environment: ete3_env
          python-version: 3.8
          auto-activate-base: false
          use-mamba: true
      - name: Test database download pipeline with stubs
        shell: bash -l {0}
        run: |
          export ETE3_HOME=$PWD/ete3_data
          nextflow run download_databases.nf \
            --download_all true \
            --overwrite true \
            -profile ci,test \
            -stub-run \
            -resume

      - name: Create mock database
        run: |
          mkdir -p test_databases/{iceberg,mobDB,phaster,prokka_db,virulencefinder_db}
          echo '{ "test_gene": { "model_type": "protein homolog model" } }' > test_databases/card.json
          echo ">seq\nATGC" > test_databases/iceberg/sequences
          touch test_databases/iceberg/status.txt
          echo "mobdb test" > test_databases/mobDB/clusters.txt
          touch test_databases/mobDB/status.txt
          echo ">phage\nATGC" > test_databases/phaster/sequences
          touch test_databases/phaster/status.txt
          touch test_databases/prokka_db/PGAP_NCBI.hmm
          touch test_databases/prokka_db/status.txt
          echo ">gene\nATGC" > test_databases/virulencefinder_db/virulence_ecoli.fsa
          touch test_databases/virulencefinder_db/status.txt
      - name: Run dry run test of pipeline
        run: |
          nextflow run pipeline.nf \
            --contigs "test_data/*.fa" \
            --card_json test_databases/card.json \
            --mobDB test_databases/mobDB \
            --virulencefinderDB test_databases/virulencefinder_db \
            --icebergDB test_databases/iceberg \
            --prokkaDB test_databases/prokka_db \
            --outDir test_output \
            -profile test,ci -stub-run


      - name: List downloaded database stubs
        run: |
          echo "Downloaded stubbed database files:"
          find work/databases
